"""Álbumes 'imprescindibles': clásicos ampliamente reconocidos, de todos los géneros.

Lista propia y editable — añade o quita a tu gusto. El selector la filtra
contra tu historial y rota con una semilla diaria.
"""

# (artista, álbum, familia)
ESSENTIALS: list[tuple[str, str, str]] = [
    ("The Beatles", "Abbey Road", "rock"),
    ("The Beatles", "Revolver", "rock"),
    ("Pink Floyd", "The Dark Side of the Moon", "rock"),
    ("Pink Floyd", "Wish You Were Here", "rock"),
    ("Led Zeppelin", "Led Zeppelin IV", "rock"),
    ("The Rolling Stones", "Exile on Main St.", "rock"),
    ("The Velvet Underground", "The Velvet Underground & Nico", "rock"),
    ("David Bowie", "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", "rock"),
    ("Queen", "A Night at the Opera", "rock"),
    ("Radiohead", "OK Computer", "rock"),
    ("Radiohead", "Kid A", "rock"),
    ("Nirvana", "Nevermind", "rock"),
    ("The Jimi Hendrix Experience", "Are You Experienced", "rock"),
    ("The Doors", "The Doors", "rock"),
    ("Neil Young", "After the Gold Rush", "folk"),
    ("Bob Dylan", "Highway 61 Revisited", "folk"),
    ("Bob Dylan", "Blood on the Tracks", "folk"),
    ("Joni Mitchell", "Blue", "folk"),
    ("Leonard Cohen", "Songs of Leonard Cohen", "folk"),
    ("Simon & Garfunkel", "Bridge Over Troubled Water", "folk"),
    ("Johnny Cash", "At Folsom Prison", "folk"),
    ("Ramones", "Ramones", "punk"),
    ("The Clash", "London Calling", "punk"),
    ("Sex Pistols", "Never Mind the Bollocks, Here's the Sex Pistols", "punk"),
    ("Television", "Marquee Moon", "punk"),
    ("Joy Division", "Unknown Pleasures", "punk"),
    ("Fugazi", "Repeater", "punk"),
    ("Black Sabbath", "Paranoid", "metal"),
    ("Metallica", "Master of Puppets", "metal"),
    ("Iron Maiden", "The Number of the Beast", "metal"),
    ("Slayer", "Reign in Blood", "metal"),
    ("Pixies", "Doolittle", "indie"),
    ("Sonic Youth", "Daydream Nation", "indie"),
    ("My Bloody Valentine", "Loveless", "indie"),
    ("The Smiths", "The Queen Is Dead", "indie"),
    ("Arcade Fire", "Funeral", "indie"),
    ("The Strokes", "Is This It", "indie"),
    ("Neutral Milk Hotel", "In the Aeroplane Over the Sea", "indie"),
    ("Miles Davis", "Kind of Blue", "jazz"),
    ("John Coltrane", "A Love Supreme", "jazz"),
    ("Charles Mingus", "The Black Saint and the Sinner Lady", "jazz"),
    ("Dave Brubeck", "Time Out", "jazz"),
    ("Herbie Hancock", "Head Hunters", "jazz"),
    ("Stan Getz", "Getz/Gilberto", "jazz"),
    ("Marvin Gaye", "What's Going On", "soul"),
    ("Stevie Wonder", "Songs in the Key of Life", "soul"),
    ("Aretha Franklin", "I Never Loved a Man the Way I Love You", "soul"),
    ("Prince", "Purple Rain", "soul"),
    ("James Brown", "Live at the Apollo", "soul"),
    ("D'Angelo", "Voodoo", "soul"),
    ("Amy Winehouse", "Back to Black", "soul"),
    ("Michael Jackson", "Thriller", "pop"),
    ("Madonna", "Like a Prayer", "pop"),
    ("ABBA", "Arrival", "pop"),
    ("Fleetwood Mac", "Rumours", "pop"),
    ("Kate Bush", "Hounds of Love", "pop"),
    ("Beyoncé", "Lemonade", "pop"),
    ("Kraftwerk", "Trans-Europe Express", "electronic"),
    ("Daft Punk", "Discovery", "electronic"),
    ("Aphex Twin", "Selected Ambient Works 85-92", "electronic"),
    ("The Prodigy", "The Fat of the Land", "electronic"),
    ("Massive Attack", "Mezzanine", "electronic"),
    ("Boards of Canada", "Music Has the Right to Children", "electronic"),
    ("Björk", "Homogenic", "electronic"),
    ("Public Enemy", "It Takes a Nation of Millions to Hold Us Back", "hiphop"),
    ("Nas", "Illmatic", "hiphop"),
    ("Wu-Tang Clan", "Enter the Wu-Tang (36 Chambers)", "hiphop"),
    ("A Tribe Called Quest", "The Low End Theory", "hiphop"),
    ("Kendrick Lamar", "To Pimp a Butterfly", "hiphop"),
    ("OutKast", "Aquemini", "hiphop"),
    ("Lauryn Hill", "The Miseducation of Lauryn Hill", "hiphop"),
    ("Bob Marley & The Wailers", "Exodus", "reggae"),
    ("Bob Marley & The Wailers", "Legend", "reggae"),
    ("Muddy Waters", "At Newport 1960", "blues"),
    ("B.B. King", "Live at the Regal", "blues"),
    ("Robert Johnson", "King of the Delta Blues Singers", "blues"),
    ("Buena Vista Social Club", "Buena Vista Social Club", "latin"),
    ("Paco de Lucía", "Entre dos aguas", "latin"),
    ("Camarón de la Isla", "La leyenda del tiempo", "latin"),
    ("Rosalía", "El mal querer", "latin"),
    ("Héroes del Silencio", "Senderos de traición", "rock"),
    ("Fela Kuti", "Zombie", "world"),
    ("Ali Farka Touré", "Talking Timbuktu", "world"),
    ("Glenn Gould", "Bach: The Goldberg Variations (1981)", "classical"),
    ("Arvo Pärt", "Tabula Rasa", "classical"),
]
